setting_0:
  speed_gain:       0.6
  cross_key_V:      crawler_move
  cross_key_H:      crawler_turn
  L1andL_stick_V:   crawler_move
  L1andR_stick_H:   crawler_turn
  L_stick_H:        arm_base_YAW
  R_stick_H:        1st_joint_YAW
  L_stick_V:        1st_joint_PITCH
  R_stick_V:        2nd_joint_PITCH
  Y_A_button:       end_effector_PITCH
  X_B_button:       end_effector_YAW
  L1andX_B_button:  end_effector_ROLL
  R1andR2:          end_effector_motion
  option_button:    switch_arm
