PS4:
  Stick_1:        # 左アナログスティック
  Stick_2:        # 右アナログスティック
  POV_up:         # デジタル十字キー 上
  POV_right:      # デジタル十字キー 右
  POV_down:       # デジタル十字キー 下
  POV_left:       # デジタル十字キー 左
  Button_1:       # ×
  Button_2:       # ❍
  Button_3:       # □
  Button_4:       # △
  Button_5:       # L1
  Button_6:       # R1
  Button_7:       # option
  Button_8:       # start
  Button_9:       # L3
  Button_10:      # R3
  Button_11:      # L2
  Button_12:      # R2
  Button_13:      # Home