config_0:
  stick_left:           /RTRDoubleArmV7/base_controller/cmd_vel     # 左スティック
  stick_right:          none                                        # 右スティック
  button_up_down:       none                                        # 十字キー 上下
  button_left_right:    none                                        # 十字キー 左右
  button_A:             none                                        # ×
  button_B:             none                                        # ❍
  button_X:             none                                        # □
  button_Y:             none                                        # △
  button_l1:            none                                        # L1
  button_r1:            none                                        # R1
  button_l2:            none                                        # L2
  button_r2:            none                                        # R2
  button_l3:            none                                        # L3
  button_r3:            none                                        # R3
  button_option:        state_button                                # option
  button_start:         none                                        # start
  button_home:          none                                        # home
config_1:
  stick_left:           /RTRDoubleArmV7/base_controller/cmd_vel     # 左スティック
  stick_right:          none                                        # 右スティック
  button_up_down:       none                                        # 十字キー 上下
  button_left_right:    none                                        # 十字キー 左右
  button_A:             none                                        # ×
  button_B:             none                                        # ❍
  button_X:             none                                        # □
  button_Y:             none                                        # △
  button_l1:            none                                        # L1
  button_r1:            none                                        # R1
  button_l2:            none                                        # L2
  button_r2:            none                                        # R2
  button_l3:            none                                        # L3
  button_r3:            none                                        # R3
  button_option:        state_button                                # option
  button_start:         none                                        # start
  button_home:          none                                        # home