key_names:
  - "stick_left_H"
  - "stick_left_V"
  - "button_l2"
  - "stick_right_H"
  - "stick_right_V"
  - "button_r2"
  - "button_H"
  - "button_V"
  - "button_A"
  - "button_B"
  - "button_Y"
  - "button_X"
  - "button_l1"
  - "button_r1"
  - "button_l2"
  - "button_r2"
  - "button_option"
  - "button_start"
  - "button_home"
  - "button_l3"
  - "button_r3"