Xbox:
  Stick_1:        # 左アナログスティック
  Stick_2:        # 右アナログスティック
  POV_up:         # デジタル十字キー 上
  POV_right:      # デジタル十字キー 右
  POV_down:       # デジタル十字キー 下
  POV_left:       # デジタル十字キー 左
  Button_1:       # A
  Button_2:       # B
  Button_3:       # X
  Button_4:       # Y
  Button_5:       # LB
  Button_6:       # RB
  Button_7:       # back
  Button_8:       # start
  Button_9:       # 左アナログスティックの中心を押した場合
  Button_10:      # 右アナログスティックの中心を押した場合
  Button_11:      # LT (左トリガー）
  Button_12:      # RT (右トリガー)
  Button_13:      # XBox (銀色のガイド）ボタン